const userData = {
  githubUsername: "gml3ff",
  name: "lupton.io",
  designation: "A Personal Homepage",
  avatarUrl: "/avatar.png",
  email: "morgan@lupton.io",
  phone: "+1 434 209 0123",
  address: "Washington, D.C., United States",
  projects: [
    {
      title: "Tailwind Master Kit",
      link: "https://tailwindmasterkit.com",
      imgUrl: "/tmk.jpg",
    },
    {
      title: "PlaceholderTech",
      link: "https://placeholdertech.in",
      imgUrl: "/placeholdertech.png",
    },
    {
      title: "Portfolio",
      link: "https://manuarora.in",
      imgUrl: "/portfolio.png",
    },
    {
      title: "CovidRescue",
      link: "https://covidrescue.co.in",
      imgUrl: "/covidrescue.png",
    },
    {
      title: "Algochurn",
      link: "https://algochurn.com",
      imgUrl: "/algochurn.png",
    },
    {
      title: "Playground",
      link: "https://play.placeholdertech.in",
      imgUrl: "/playground.png",
    },
    {
      title: "Feedmeback",
      link: "https://feedmeback.vercel.app",
      imgUrl: "/feedmeback.png",
    },
    {
      title: "Devmedium",
      link: "https://devmedium.vercel.app",
      imgUrl: "/devmedium.png",
    },
  ],
  about: {
    title:
      "Product-focused Sales Engineer",
    description: [
      `With a background in cloud operations engineering I have experience developing and deploying large scale applications with an emphasis on reliability and performance. I have carried these skills over to the sales side as well: using my knowledge of SRE principles to sell monitoring solutions to a wide variety of organizations ranging from eCommerce platforms, to Finance and Healthcare`,
      `Despite my experience in the software realm, I also have a penchant for product design in the physical world. I have taught myself 3D modeling using Fusion360 and have brought these models into reality using my 3D printer. Beyond the design of the models themselves, I will frequently construct projects that involve some kind of electronic hardware (e.g. Arduinos, Raspberry Pis, etc.). Everything from the soldering of wires and PCBs to the design of the software, I do it all. These projects have ranged from simple household appliances like vacuum accessories, to more complex tasks like building MIDI interfaces for Ableton Live.`,
      `Beyond these pursuits, I spend a great deal of my spare time DJ'ing and producing music. My wife and I host a monthly radio show on Eaton Radio here in D.C., and I play live around the area as well (mainly doing all-vinyl sets). I make my own music within Ableton, but do also enjoy using hardware synthesizers on ocassion (namely my Yamaha SY77).`,
    ],
    currentProject: "",
    currentProjectUrl: "",
  },
  experience: [
    {
      title: "Sales Engineering Regional Manager",
      company: "Datadog Inc",
      year: "2022 - present",
      companyLink: "https://www.datadoghq.com/",
      desc: "Currently managing staffing, onboarding, and other supervisory duties for a team of 5 sales engineers across the Mid Atlantic and Federal regions. Continuing to meet with customers in strategic opportunities.",
      tech: ["Generally the same as in IC role listed below"],
      highlights: ["Mentored new and existing SEs through complex technical evaluations, leading to many of their first deals over $25K net new MRR","Mentored and onboarded a new sales director and 5 sales representatives"],
    },
    {
      title: "Sales Engineering Team Lead",
      company: "Datadog Inc",
      year: "2021 - 2022",
      companyLink: "https://www.datadoghq.com/",
      desc: "Served as Team Lead for Mid Atlantic, Ohio Valley, and Federal teams. Onboarded new SEs, and supervised strategic opportunities.",
      tech: ["Generally the same as in IC role listed below"],
      highlights: ["Developed new customer acquisition strategies for our expanding product portfolio in collaboration with the sales team","Interviewed, onboarded, and trained 7 new sales engineers for Latin America and Southeast teams"],
    },
    {
      title: "Enterprise Sales Engineer",
      company: "Datadog Inc",
      year: "2019 - 2021",
      companyLink: "https://www.datadoghq.com/",
      desc: "Conducted demos, organized proof of concepts, and performed techinical implementations of Datadog's solution to acquire new business and expand existing install bases",
      tech: ["Kubernetes","Elastic Beanstalk","OpenShift","Python","AWS","Azure","Terraform","Ansible","MongoDB","Postgres",".NET", "AWS Lambda", "Azure App Services"],
      highlights: ["Lead Sales Engineer on 35 closed won opportunities netting over $600K MRR in net new revenue as an individual contributor (slightly under $1 million net new MRR if including assists)","Lead Sales Engineer on 2 deals mentioned in DDOG earnings calls and assisted in 2 others","Shepherded customers through our FedRAMP authorization, closing deals both before and after authorization was finalized","Evangelized Datadog at various tradeshows"],
    },
    {
      title: "Cloud Operations Engineer",
      company: "SocialTables",
      year: "2018 - 2019",
      companyLink: "https://www.socialtables.com/",
      desc: "Optimized AWS compute, networking, and storage resources for cost and availability to support a WebGL event diagramming solution",
      tech: ["AWS","ECS","Cloudfront","HAProxy","RethinkDB","Docker","Circle CI","Terraform","Ansible","Elasticsearch","GitHub","NewRelic","Prometheus","Grafana"],
      highlights: ["Built an easily-deployable staging environment using Terraform for developers to test new features against realistic, up-to-date copies of production data","Created application and infrastructure monitoring alerts & dashboards using New Relic and templatized them using Terraform", "Automated AWS infrastructure using Ansible & Terraform"],
    },
    {
      title: "Linux Systems Engineer",
      company: "Discogs BV",
      year: "2016 - 2017",
      companyLink: "https://www.discogs.com/",
      desc: "Served as a site reliability engineer (SRE) for the world's largest eCommerce platform for vinyl records",
      tech: ["AWS","Chef","Fastly","HAProxy","CentOS","Elasticsearch","MySQL","MemcacheD","Cisco ASA","Juniper Switches","Tunnelblick VPN","GitHub","Datadog"],
      highlights: ["Mitigated a large-scale security threat by forcing 2 factor authentication, encrypting storage media, and rotating keys within a 72-hour timeframe","Managed & configured a highly available cloud and datacenter infrastructure using Chef","Managed image caching using Fastly’s Content Delivery Network (CDN)","Mitigated API abuse by working with Discog’s largest customers  by tweaking user agent & rate-limiting rules in HAProxy"],
    },
    {
      title: "Associate Consultant",
      company: "Red Hat Inc.",
      year: "2015 - 2016",
      companyLink: "https://www.redhat.com/en",
      desc: "Provided post-sales implementation support and advisory for Red Hat's enterprise customers",
      tech: ["Java EE", "JUnit", "Red Hat Enterprise Linux (RHEL)", "Jenkins", "OpenStack Platform", "JBoss EAP", "JBoss BRMS", "Cucumber", "TortoiseSVN"],
      highlights: ["Wrote & maintained enterprise Java applications hosted on JBoss EAP","Used OpenStack for network function virtualization (NFV) within a major telecom provider's datacenter","Wrote Drools Rules for customers in JBoss BRMS"],
    },
    {
      title: "CEOS Intern",
      company: "NASA Langley Research Center",
      year: "2013",
      desc: "Developed PHP code for the Committee on Earth Observation Satellites web-based satellite swath coverage tool COVE (CEOS Visualization Environment)",
      companyLink: "https://www.nasa.gov/langley",
      tech: ["PHP","IIS",".NET Framework","Web Development"],
      highlights: ["Ported a .NET Satellite Swath calculation tool to Java for cross-platform usage"],
    },
  ],
  resumeUrl:
    "https://docs.google.com/document/d/1l8Xe1A__T47zmE3bd5D3gYfUWJq-rdWBZ8IgMonN11k/edit?usp=sharing",
  socialLinks: {
    instagram: "",
    twitter: "",
    linkedin: "https://www.linkedin.com/in/morgan-lupton/",
    github: "https://github.com/gml3ff",
    facebook: "",
  },
};

export default userData;
